// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toplevel_cordic_atan2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y0_V,
        x0_V,
        zn_V_read,
        ap_return
);

parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st4_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv18_0 = 18'b000000000000000000;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv16_E6DF = 16'b1110011011011111;
parameter    ap_const_lv16_1921 = 16'b1100100100001;
parameter    ap_const_lv16_3243 = 16'b11001001000011;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv16_CDBD = 16'b1100110110111101;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] y0_V;
input  [17:0] x0_V;
input  [15:0] zn_V_read;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_20;
wire   [3:0] atan_2Mi_V_address0;
reg    atan_2Mi_V_ce0;
wire   [11:0] atan_2Mi_V_q0;
reg   [15:0] p_Val2_5_reg_98;
reg   [17:0] p_Val2_6_reg_110;
reg   [17:0] p_Val2_s_reg_119;
reg   [3:0] p_3_reg_128;
wire   [17:0] x_V_1_fu_171_p3;
wire   [17:0] y_V_1_fu_193_p3;
wire   [0:0] tmp_167_fu_201_p2;
reg   [0:0] tmp_167_reg_513;
wire   [0:0] tmp_168_fu_207_p2;
reg   [0:0] tmp_168_reg_517;
wire   [0:0] sel_tmp8_fu_303_p2;
reg   [0:0] sel_tmp8_reg_521;
wire   [2:0] quadrant_3_fu_323_p3;
reg   [2:0] quadrant_3_reg_525;
wire   [15:0] storemerge_cast_cast_fu_331_p3;
wire   [15:0] storemerge1_cast_cast_fu_339_p3;
wire   [0:0] exitcond_fu_347_p2;
reg   [0:0] exitcond_reg_542;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_83;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
wire   [3:0] i_V_fu_353_p2;
wire   [0:0] dneg_fu_359_p2;
reg   [0:0] dneg_reg_551;
wire   [17:0] yp_V_3_fu_416_p3;
wire   [17:0] xp_V_3_fu_424_p3;
wire   [15:0] zp_V_3_fu_448_p3;
reg   [15:0] ssdm_int_V_write_assign_phi_fu_142_p12;
reg   [15:0] ssdm_int_V_write_assign_reg_139;
reg    ap_sig_cseq_ST_st4_fsm_2;
reg    ap_sig_124;
wire   [0:0] tmp_175_fu_455_p2;
wire   [15:0] p_Val2_s_26_fu_491_p2;
wire   [0:0] tmp_177_fu_460_p2;
wire   [15:0] p_Val2_10_fu_484_p2;
wire   [15:0] phitmp_fu_476_p3;
wire   [63:0] tmp_176_fu_393_p1;
wire   [0:0] tmp_fu_157_p3;
wire   [17:0] x_V_1_1_fu_165_p2;
wire   [0:0] tmp_174_fu_179_p3;
wire   [17:0] y_V_fu_187_p2;
wire   [0:0] tmp_169_fu_213_p2;
wire   [0:0] tmp_170_fu_219_p2;
wire   [17:0] tmp_172_fu_237_p2;
wire   [0:0] tmp_s_fu_225_p2;
wire   [0:0] tmp_173_fu_251_p2;
wire   [0:0] tmp_98_fu_265_p2;
wire   [2:0] p_s_fu_257_p3;
wire   [0:0] tmp_171_fu_231_p2;
wire   [0:0] sel_tmp2_fu_279_p2;
wire   [0:0] sel_tmp7_demorgan_fu_291_p2;
wire   [0:0] tmp_180_fu_243_p3;
wire   [0:0] sel_tmp7_fu_297_p2;
wire   [0:0] sel_tmp3_fu_285_p2;
wire   [0:0] tmp_99_fu_317_p2;
wire   [2:0] sel_tmp4_cast_fu_309_p3;
wire   [2:0] sel_tmp_fu_271_p3;
wire   [17:0] sh_cast_fu_365_p1;
wire   [17:0] p_Val2_7_fu_369_p2;
wire   [17:0] p_Val2_8_fu_381_p2;
wire   [17:0] p_Val2_9_fu_398_p2;
wire   [17:0] yp_V_fu_387_p2;
wire   [17:0] yp_V_1_fu_410_p2;
wire   [17:0] xp_V_fu_375_p2;
wire   [17:0] xp_V_1_fu_404_p2;
wire   [15:0] p_Val2_51_cast_fu_432_p1;
wire   [15:0] zp_V_1_1_fu_436_p2;
wire   [15:0] zp_V_1_fu_442_p2;
wire   [0:0] tmp_178_fu_465_p2;
wire   [15:0] p_Val2_11_fu_470_p2;
reg   [15:0] ap_return_preg;
reg   [2:0] ap_NS_fsm;
reg    ap_sig_393;
reg    ap_sig_396;
reg    ap_sig_398;
reg    ap_sig_363;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'b1;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_return_preg = 16'b0000000000000000;
end

toplevel_cordic_atan2_atan_2Mi_V #(
    .DataWidth( 12 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
atan_2Mi_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(atan_2Mi_V_address0),
    .ce0(atan_2Mi_V_ce0),
    .q0(atan_2Mi_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(1'b0 == exitcond_fu_347_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b0 == exitcond_fu_347_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(1'b0 == exitcond_fu_347_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= ap_const_lv16_0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st4_fsm_2)) begin
            ap_return_preg <= ssdm_int_V_write_assign_phi_fu_142_p12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_fu_347_p2))) begin
        p_3_reg_128 <= i_V_fu_353_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
        p_3_reg_128 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_reg_542))) begin
        p_Val2_5_reg_98 <= zp_V_3_fu_448_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
        p_Val2_5_reg_98 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_fu_347_p2))) begin
        p_Val2_6_reg_110 <= yp_V_3_fu_416_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
        p_Val2_6_reg_110 <= y_V_1_fu_193_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_fu_347_p2))) begin
        p_Val2_s_reg_119 <= xp_V_3_fu_424_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
        p_Val2_s_reg_119 <= x_V_1_fu_171_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_2) & (1'b0 == tmp_175_fu_455_p2) & (tmp_167_reg_513 == 1'b0) & (tmp_168_reg_517 == 1'b0) & (1'b0 == tmp_177_fu_460_p2) & (1'b0 == sel_tmp8_reg_521))) begin
        ssdm_int_V_write_assign_reg_139 <= phitmp_fu_476_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_2) & (1'b0 == tmp_175_fu_455_p2) & (tmp_167_reg_513 == 1'b0) & (tmp_168_reg_517 == 1'b0) & (1'b0 == tmp_177_fu_460_p2) & ~(1'b0 == sel_tmp8_reg_521))) begin
        ssdm_int_V_write_assign_reg_139 <= p_Val2_10_fu_484_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_2) & (1'b0 == tmp_175_fu_455_p2) & (tmp_167_reg_513 == 1'b0) & (tmp_168_reg_517 == 1'b0) & ~(1'b0 == tmp_177_fu_460_p2))) begin
        ssdm_int_V_write_assign_reg_139 <= p_Val2_s_26_fu_491_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_2) & ~(1'b0 == tmp_175_fu_455_p2) & (tmp_167_reg_513 == 1'b0) & (tmp_168_reg_517 == 1'b0))) begin
        ssdm_int_V_write_assign_reg_139 <= p_Val2_5_reg_98;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & ~(tmp_168_fu_207_p2 == 1'b0))) begin
        ssdm_int_V_write_assign_reg_139 <= storemerge_cast_cast_fu_331_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & ~(tmp_167_fu_201_p2 == 1'b0))) begin
        ssdm_int_V_write_assign_reg_139 <= storemerge1_cast_cast_fu_339_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b0 == exitcond_fu_347_p2))) begin
        dneg_reg_551 <= dneg_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1)) begin
        exitcond_reg_542 <= exitcond_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
        quadrant_3_reg_525 <= quadrant_3_fu_323_p3;
        sel_tmp8_reg_521 <= sel_tmp8_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        tmp_167_reg_513 <= tmp_167_fu_201_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0))) begin
        tmp_168_reg_517 <= tmp_168_fu_207_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | (1'b1 == ap_sig_cseq_ST_st4_fsm_2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_2)) begin
        ap_return = ssdm_int_V_write_assign_phi_fu_142_p12;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (ap_sig_83) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_20) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_124) begin
        ap_sig_cseq_ST_st4_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        atan_2Mi_V_ce0 = 1'b1;
    end else begin
        atan_2Mi_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_363) begin
        if (ap_sig_398) begin
            ssdm_int_V_write_assign_phi_fu_142_p12 = phitmp_fu_476_p3;
        end else if (ap_sig_396) begin
            ssdm_int_V_write_assign_phi_fu_142_p12 = p_Val2_10_fu_484_p2;
        end else if (ap_sig_393) begin
            ssdm_int_V_write_assign_phi_fu_142_p12 = p_Val2_s_26_fu_491_p2;
        end else if (~(1'b0 == tmp_175_fu_455_p2)) begin
            ssdm_int_V_write_assign_phi_fu_142_p12 = p_Val2_5_reg_98;
        end else begin
            ssdm_int_V_write_assign_phi_fu_142_p12 = ssdm_int_V_write_assign_reg_139;
        end
    end else begin
        ssdm_int_V_write_assign_phi_fu_142_p12 = ssdm_int_V_write_assign_reg_139;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if ((~(ap_start == 1'b0) & (~(tmp_168_fu_207_p2 == 1'b0) | ~(tmp_167_fu_201_p2 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_st4_fsm_2;
            end else if ((~(ap_start == 1'b0) & (tmp_167_fu_201_p2 == 1'b0) & (tmp_168_fu_207_p2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(1'b0 == exitcond_fu_347_p2))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_2;
            end
        end
        ap_ST_st4_fsm_2 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_124 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_20 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_363 = ((1'b1 == ap_sig_cseq_ST_st4_fsm_2) & (tmp_167_reg_513 == 1'b0) & (tmp_168_reg_517 == 1'b0));
end

always @ (*) begin
    ap_sig_393 = ((1'b0 == tmp_175_fu_455_p2) & ~(1'b0 == tmp_177_fu_460_p2));
end

always @ (*) begin
    ap_sig_396 = ((1'b0 == tmp_175_fu_455_p2) & (1'b0 == tmp_177_fu_460_p2) & ~(1'b0 == sel_tmp8_reg_521));
end

always @ (*) begin
    ap_sig_398 = ((1'b0 == tmp_175_fu_455_p2) & (1'b0 == tmp_177_fu_460_p2) & (1'b0 == sel_tmp8_reg_521));
end

always @ (*) begin
    ap_sig_83 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign atan_2Mi_V_address0 = tmp_176_fu_393_p1;

assign dneg_fu_359_p2 = (($signed(p_Val2_6_reg_110) > $signed(18'b000000000000000000)) ? 1'b1 : 1'b0);

assign exitcond_fu_347_p2 = ((p_3_reg_128 == ap_const_lv4_9) ? 1'b1 : 1'b0);

assign i_V_fu_353_p2 = (p_3_reg_128 + ap_const_lv4_1);

assign p_Val2_10_fu_484_p2 = ($signed(p_Val2_5_reg_98) + $signed(ap_const_lv16_CDBD));

assign p_Val2_11_fu_470_p2 = (ap_const_lv16_0 - p_Val2_5_reg_98);

assign p_Val2_51_cast_fu_432_p1 = atan_2Mi_V_q0;

assign p_Val2_7_fu_369_p2 = p_Val2_6_reg_110 >> sh_cast_fu_365_p1;

assign p_Val2_8_fu_381_p2 = $signed(p_Val2_s_reg_119) >>> sh_cast_fu_365_p1;

assign p_Val2_9_fu_398_p2 = $signed(p_Val2_6_reg_110) >>> sh_cast_fu_365_p1;

assign p_Val2_s_26_fu_491_p2 = (ap_const_lv16_3243 - p_Val2_5_reg_98);

assign p_s_fu_257_p3 = ((tmp_s_fu_225_p2[0:0] === 1'b1) ? ap_const_lv3_1 : ap_const_lv3_4);

assign phitmp_fu_476_p3 = ((tmp_178_fu_465_p2[0:0] === 1'b1) ? p_Val2_11_fu_470_p2 : zn_V_read);

assign quadrant_3_fu_323_p3 = ((tmp_99_fu_317_p2[0:0] === 1'b1) ? sel_tmp4_cast_fu_309_p3 : sel_tmp_fu_271_p3);

assign sel_tmp2_fu_279_p2 = (tmp_s_fu_225_p2 ^ 1'b1);

assign sel_tmp3_fu_285_p2 = (tmp_171_fu_231_p2 & sel_tmp2_fu_279_p2);

assign sel_tmp4_cast_fu_309_p3 = ((sel_tmp8_fu_303_p2[0:0] === 1'b1) ? ap_const_lv3_3 : ap_const_lv3_2);

assign sel_tmp7_demorgan_fu_291_p2 = (tmp_s_fu_225_p2 | tmp_171_fu_231_p2);

assign sel_tmp7_fu_297_p2 = (sel_tmp7_demorgan_fu_291_p2 ^ 1'b1);

assign sel_tmp8_fu_303_p2 = (tmp_180_fu_243_p3 & sel_tmp7_fu_297_p2);

assign sel_tmp_fu_271_p3 = ((tmp_98_fu_265_p2[0:0] === 1'b1) ? p_s_fu_257_p3 : ap_const_lv3_0);

assign sh_cast_fu_365_p1 = p_3_reg_128;

assign storemerge1_cast_cast_fu_339_p3 = ((tmp_fu_157_p3[0:0] === 1'b1) ? ap_const_lv16_3243 : ap_const_lv16_0);

assign storemerge_cast_cast_fu_331_p3 = ((tmp_174_fu_179_p3[0:0] === 1'b1) ? ap_const_lv16_E6DF : ap_const_lv16_1921);

assign tmp_167_fu_201_p2 = ((y0_V == ap_const_lv18_0) ? 1'b1 : 1'b0);

assign tmp_168_fu_207_p2 = ((x0_V == ap_const_lv18_0) ? 1'b1 : 1'b0);

assign tmp_169_fu_213_p2 = (($signed(x0_V) > $signed(18'b000000000000000000)) ? 1'b1 : 1'b0);

assign tmp_170_fu_219_p2 = (($signed(y0_V) > $signed(18'b000000000000000000)) ? 1'b1 : 1'b0);

assign tmp_171_fu_231_p2 = (tmp_fu_157_p3 & tmp_170_fu_219_p2);

assign tmp_172_fu_237_p2 = (y0_V & x0_V);

assign tmp_173_fu_251_p2 = (tmp_169_fu_213_p2 & tmp_174_fu_179_p3);

assign tmp_174_fu_179_p3 = y0_V[ap_const_lv32_11];

assign tmp_175_fu_455_p2 = ((quadrant_3_reg_525 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign tmp_176_fu_393_p1 = p_3_reg_128;

assign tmp_177_fu_460_p2 = ((quadrant_3_reg_525 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign tmp_178_fu_465_p2 = ((quadrant_3_reg_525 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign tmp_180_fu_243_p3 = tmp_172_fu_237_p2[ap_const_lv32_11];

assign tmp_98_fu_265_p2 = (tmp_s_fu_225_p2 | tmp_173_fu_251_p2);

assign tmp_99_fu_317_p2 = (sel_tmp8_fu_303_p2 | sel_tmp3_fu_285_p2);

assign tmp_fu_157_p3 = x0_V[ap_const_lv32_11];

assign tmp_s_fu_225_p2 = (tmp_169_fu_213_p2 & tmp_170_fu_219_p2);

assign x_V_1_1_fu_165_p2 = (ap_const_lv18_0 - x0_V);

assign x_V_1_fu_171_p3 = ((tmp_fu_157_p3[0:0] === 1'b1) ? x_V_1_1_fu_165_p2 : x0_V);

assign xp_V_1_fu_404_p2 = (p_Val2_s_reg_119 - p_Val2_9_fu_398_p2);

assign xp_V_3_fu_424_p3 = ((dneg_fu_359_p2[0:0] === 1'b1) ? xp_V_fu_375_p2 : xp_V_1_fu_404_p2);

assign xp_V_fu_375_p2 = (p_Val2_7_fu_369_p2 + p_Val2_s_reg_119);

assign y_V_1_fu_193_p3 = ((tmp_174_fu_179_p3[0:0] === 1'b1) ? y_V_fu_187_p2 : y0_V);

assign y_V_fu_187_p2 = (ap_const_lv18_0 - y0_V);

assign yp_V_1_fu_410_p2 = (p_Val2_8_fu_381_p2 + p_Val2_6_reg_110);

assign yp_V_3_fu_416_p3 = ((dneg_fu_359_p2[0:0] === 1'b1) ? yp_V_fu_387_p2 : yp_V_1_fu_410_p2);

assign yp_V_fu_387_p2 = (p_Val2_6_reg_110 - p_Val2_8_fu_381_p2);

assign zp_V_1_1_fu_436_p2 = (p_Val2_51_cast_fu_432_p1 + p_Val2_5_reg_98);

assign zp_V_1_fu_442_p2 = (p_Val2_5_reg_98 - p_Val2_51_cast_fu_432_p1);

assign zp_V_3_fu_448_p3 = ((dneg_reg_551[0:0] === 1'b1) ? zp_V_1_1_fu_436_p2 : zp_V_1_fu_442_p2);

endmodule //toplevel_cordic_atan2
