# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /usr/userfs/a/az579/slam-xilinx/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /usr/userfs/a/az579/slam-xilinx/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
set_property ip_repo_paths /usr/userfs/a/az579/slam-xilinx/jacobian-accelerator/jacobian-accelerator/impl [current_project]
add_files /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/vivado.bd
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_processing_system7_0_0/vivado_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_toplevel_0_0/constraints/toplevel_ooc.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_rst_processing_system7_0_100M_0/vivado_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_rst_processing_system7_0_100M_0/vivado_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_rst_processing_system7_0_100M_0/vivado_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_auto_pc_0/vivado_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/ip/vivado_auto_pc_1/vivado_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/vivado_ooc.xdc]
set_property is_locked true [get_files /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/vivado.bd]

read_verilog -library xil_defaultlib /usr/userfs/a/az579/slam-xilinx/vivado/vivado.srcs/sources_1/bd/vivado/hdl/vivado_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top vivado_wrapper -part xc7z045ffg900-2


write_checkpoint -force -noxdef vivado_wrapper.dcp

catch { report_utilization -file vivado_wrapper_utilization_synth.rpt -pb vivado_wrapper_utilization_synth.pb }
