// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_defa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_V_address0,
        A_V_ce0,
        A_V_q0,
        B_V_address0,
        B_V_ce0,
        B_V_q0,
        aux_V_address0,
        aux_V_ce0,
        aux_V_we0,
        aux_V_d0
);

parameter    ap_ST_fsm_state1 = 3'b1;
parameter    ap_ST_fsm_pp0_stage0 = 3'b10;
parameter    ap_ST_fsm_state8 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_3C = 32'b111100;
parameter    ap_const_lv32_2 = 32'b10;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] A_V_address0;
output   A_V_ce0;
input  [31:0] A_V_q0;
output  [1:0] B_V_address0;
output   B_V_ce0;
input  [31:0] B_V_q0;
output  [1:0] aux_V_address0;
output   aux_V_ce0;
output   aux_V_we0;
output  [31:0] aux_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg A_V_ce0;
reg B_V_ce0;
reg aux_V_ce0;
reg aux_V_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [3:0] indvar_flatten2_reg_97;
reg   [1:0] Row_assign_reg_108;
reg   [3:0] indvar_flatten_reg_119;
reg   [1:0] Col_assign_reg_130;
reg   [1:0] Col_assign_3_reg_141;
wire   [0:0] exitcond_flatten2_fu_152_p2;
reg   [0:0] exitcond_flatten2_reg_388;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond_flatten2_reg_388;
reg   [0:0] ap_pipeline_reg_pp0_iter2_exitcond_flatten2_reg_388;
reg   [0:0] ap_pipeline_reg_pp0_iter3_exitcond_flatten2_reg_388;
reg   [0:0] ap_pipeline_reg_pp0_iter4_exitcond_flatten2_reg_388;
wire   [3:0] indvar_flatten_next2_fu_158_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [1:0] tmp_mid2_v_fu_184_p3;
reg   [1:0] tmp_mid2_v_reg_397;
wire   [1:0] tmp_mid2_fu_242_p3;
reg   [1:0] tmp_mid2_reg_402;
reg   [1:0] aux_V_addr_reg_407;
reg   [1:0] ap_pipeline_reg_pp0_iter1_aux_V_addr_reg_407;
reg   [1:0] ap_pipeline_reg_pp0_iter2_aux_V_addr_reg_407;
reg   [1:0] ap_pipeline_reg_pp0_iter3_aux_V_addr_reg_407;
reg   [1:0] ap_pipeline_reg_pp0_iter4_aux_V_addr_reg_407;
wire   [0:0] tmp_139_fu_303_p2;
reg   [0:0] tmp_139_reg_422;
reg   [0:0] ap_pipeline_reg_pp0_iter1_tmp_139_reg_422;
reg   [0:0] ap_pipeline_reg_pp0_iter2_tmp_139_reg_422;
reg   [0:0] ap_pipeline_reg_pp0_iter3_tmp_139_reg_422;
reg   [0:0] ap_pipeline_reg_pp0_iter4_tmp_139_reg_422;
wire   [0:0] tmp_140_fu_309_p2;
reg   [0:0] tmp_140_reg_427;
reg   [0:0] ap_pipeline_reg_pp0_iter1_tmp_140_reg_427;
reg   [0:0] ap_pipeline_reg_pp0_iter2_tmp_140_reg_427;
reg   [0:0] ap_pipeline_reg_pp0_iter3_tmp_140_reg_427;
reg   [0:0] ap_pipeline_reg_pp0_iter4_tmp_140_reg_427;
wire   [1:0] k_fu_315_p2;
wire   [3:0] indvar_flatten_next_fu_327_p3;
reg  signed [31:0] cast_in_a_V_reg_441;
reg  signed [31:0] cast_in_b_V_reg_446;
wire   [63:0] grp_fu_341_p2;
reg   [63:0] r_V_reg_461;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg   [1:0] Row_assign_phi_fu_112_p4;
reg   [1:0] Col_assign_phi_fu_134_p4;
wire   [63:0] tmp_152_cast_fu_260_p1;
wire   [63:0] tmp_153_cast_fu_275_p1;
wire   [63:0] tmp_156_cast_fu_298_p1;
reg   [65:0] p_Val2_39_fu_58;
wire   [65:0] p_Val2_43_fu_359_p3;
wire   [0:0] exitcond_flatten7_fu_170_p2;
wire   [1:0] r_fu_164_p2;
wire   [2:0] tmp_fu_192_p3;
wire   [0:0] exitcond9_fu_210_p2;
wire   [0:0] not_exitcond_flatten_fu_204_p2;
wire   [1:0] Col_assign_mid_fu_176_p3;
wire   [0:0] exitcond_mid_fu_216_p2;
wire   [0:0] tmp_s_fu_228_p2;
wire   [1:0] c_fu_222_p2;
wire   [3:0] tmp_mid2_cast_fu_250_p1;
wire   [3:0] tmp_150_cast_fu_200_p1;
wire   [3:0] tmp_134_fu_254_p2;
wire   [1:0] Col_assign_3_mid2_fu_234_p3;
wire   [3:0] tmp_i_i_cast_fu_265_p1;
wire   [3:0] tmp_136_fu_269_p2;
wire   [2:0] tmp_137_fu_280_p3;
wire   [3:0] tmp_155_cast_fu_288_p1;
wire   [3:0] tmp_138_fu_292_p2;
wire   [3:0] indvar_flatten_op_fu_321_p2;
wire  signed [65:0] p_Val2_38_fu_350_p1;
wire   [65:0] p_Val2_s_fu_353_p2;
wire   [0:0] ap_CS_fsm_state8;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'b1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

toplevel_mul_32s_cud #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
toplevel_mul_32s_cud_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cast_in_b_V_reg_446),
    .din1(cast_in_a_V_reg_441),
    .ce(1'b1),
    .dout(grp_fu_341_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten2_fu_152_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_fu_152_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten2_fu_152_p2 == 1'b0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten2_fu_152_p2 == 1'b0))) begin
        Col_assign_3_reg_141 <= k_fu_315_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        Col_assign_3_reg_141 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_reg_388 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        Col_assign_reg_130 <= tmp_mid2_reg_402;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        Col_assign_reg_130 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_reg_388 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        Row_assign_reg_108 <= tmp_mid2_v_reg_397;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        Row_assign_reg_108 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten2_fu_152_p2 == 1'b0))) begin
        indvar_flatten2_reg_97 <= indvar_flatten_next2_fu_158_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        indvar_flatten2_reg_97 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten2_fu_152_p2 == 1'b0))) begin
        indvar_flatten_reg_119 <= indvar_flatten_next_fu_327_p3;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_119 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_pipeline_reg_pp0_iter1_aux_V_addr_reg_407 <= aux_V_addr_reg_407;
        ap_pipeline_reg_pp0_iter1_exitcond_flatten2_reg_388 <= exitcond_flatten2_reg_388;
        ap_pipeline_reg_pp0_iter1_tmp_139_reg_422 <= tmp_139_reg_422;
        ap_pipeline_reg_pp0_iter1_tmp_140_reg_427 <= tmp_140_reg_427;
        exitcond_flatten2_reg_388 <= exitcond_flatten2_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == 1'b1)) begin
        ap_pipeline_reg_pp0_iter2_aux_V_addr_reg_407 <= ap_pipeline_reg_pp0_iter1_aux_V_addr_reg_407;
        ap_pipeline_reg_pp0_iter2_exitcond_flatten2_reg_388 <= ap_pipeline_reg_pp0_iter1_exitcond_flatten2_reg_388;
        ap_pipeline_reg_pp0_iter2_tmp_139_reg_422 <= ap_pipeline_reg_pp0_iter1_tmp_139_reg_422;
        ap_pipeline_reg_pp0_iter2_tmp_140_reg_427 <= ap_pipeline_reg_pp0_iter1_tmp_140_reg_427;
        ap_pipeline_reg_pp0_iter3_aux_V_addr_reg_407 <= ap_pipeline_reg_pp0_iter2_aux_V_addr_reg_407;
        ap_pipeline_reg_pp0_iter3_exitcond_flatten2_reg_388 <= ap_pipeline_reg_pp0_iter2_exitcond_flatten2_reg_388;
        ap_pipeline_reg_pp0_iter3_tmp_139_reg_422 <= ap_pipeline_reg_pp0_iter2_tmp_139_reg_422;
        ap_pipeline_reg_pp0_iter3_tmp_140_reg_427 <= ap_pipeline_reg_pp0_iter2_tmp_140_reg_427;
        ap_pipeline_reg_pp0_iter4_aux_V_addr_reg_407 <= ap_pipeline_reg_pp0_iter3_aux_V_addr_reg_407;
        ap_pipeline_reg_pp0_iter4_exitcond_flatten2_reg_388 <= ap_pipeline_reg_pp0_iter3_exitcond_flatten2_reg_388;
        ap_pipeline_reg_pp0_iter4_tmp_139_reg_422 <= ap_pipeline_reg_pp0_iter3_tmp_139_reg_422;
        ap_pipeline_reg_pp0_iter4_tmp_140_reg_427 <= ap_pipeline_reg_pp0_iter3_tmp_140_reg_427;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_fu_152_p2 == 1'b0))) begin
        aux_V_addr_reg_407 <= tmp_152_cast_fu_260_p1;
        tmp_139_reg_422 <= tmp_139_fu_303_p2;
        tmp_140_reg_427 <= tmp_140_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_reg_388 == 1'b0))) begin
        cast_in_a_V_reg_441 <= A_V_q0;
        cast_in_b_V_reg_446 <= B_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter5) & (ap_pipeline_reg_pp0_iter4_exitcond_flatten2_reg_388 == 1'b0))) begin
        p_Val2_39_fu_58 <= p_Val2_43_fu_359_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_pipeline_reg_pp0_iter3_exitcond_flatten2_reg_388 == 1'b0)) begin
        r_V_reg_461 <= grp_fu_341_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten2_fu_152_p2 == 1'b0))) begin
        tmp_mid2_reg_402 <= tmp_mid2_fu_242_p3;
        tmp_mid2_v_reg_397 <= tmp_mid2_v_fu_184_p3;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        A_V_ce0 = 1'b1;
    end else begin
        A_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        B_V_ce0 = 1'b1;
    end else begin
        B_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_reg_388 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        Col_assign_phi_fu_134_p4 = tmp_mid2_reg_402;
    end else begin
        Col_assign_phi_fu_134_p4 = Col_assign_reg_130;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten2_reg_388 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        Row_assign_phi_fu_112_p4 = tmp_mid2_v_reg_397;
    end else begin
        Row_assign_phi_fu_112_p4 = Row_assign_reg_108;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter5)) begin
        aux_V_ce0 = 1'b1;
    end else begin
        aux_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b0 == ap_pipeline_reg_pp0_iter4_tmp_140_reg_427))) begin
        aux_V_we0 = 1'b1;
    end else begin
        aux_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter5) & ~(1'b1 == ap_enable_reg_pp0_iter4)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten2_fu_152_p2 == 1'b0) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten2_fu_152_p2 == 1'b0) & ~(1'b1 == ap_enable_reg_pp0_iter1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_V_address0 = tmp_153_cast_fu_275_p1;

assign B_V_address0 = tmp_156_cast_fu_298_p1;

assign Col_assign_3_mid2_fu_234_p3 = ((tmp_s_fu_228_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Col_assign_3_reg_141);

assign Col_assign_mid_fu_176_p3 = ((exitcond_flatten7_fu_170_p2[0:0] === 1'b1) ? ap_const_lv2_0 : Col_assign_phi_fu_134_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state8 = ap_CS_fsm[ap_const_lv32_2];

assign aux_V_address0 = ap_pipeline_reg_pp0_iter4_aux_V_addr_reg_407;

assign aux_V_d0 = {{p_Val2_43_fu_359_p3[ap_const_lv32_3C : ap_const_lv32_1D]}};

assign c_fu_222_p2 = (Col_assign_mid_fu_176_p3 + ap_const_lv2_1);

assign exitcond9_fu_210_p2 = ((Col_assign_3_reg_141 == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_152_p2 = ((indvar_flatten2_reg_97 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign exitcond_flatten7_fu_170_p2 = ((indvar_flatten_reg_119 == ap_const_lv4_4) ? 1'b1 : 1'b0);

assign exitcond_mid_fu_216_p2 = (exitcond9_fu_210_p2 & not_exitcond_flatten_fu_204_p2);

assign indvar_flatten_next2_fu_158_p2 = (indvar_flatten2_reg_97 + ap_const_lv4_1);

assign indvar_flatten_next_fu_327_p3 = ((exitcond_flatten7_fu_170_p2[0:0] === 1'b1) ? ap_const_lv4_1 : indvar_flatten_op_fu_321_p2);

assign indvar_flatten_op_fu_321_p2 = (indvar_flatten_reg_119 + ap_const_lv4_1);

assign k_fu_315_p2 = (Col_assign_3_mid2_fu_234_p3 + ap_const_lv2_1);

assign not_exitcond_flatten_fu_204_p2 = (exitcond_flatten7_fu_170_p2 ^ 1'b1);

assign p_Val2_38_fu_350_p1 = $signed(r_V_reg_461);

assign p_Val2_43_fu_359_p3 = ((ap_pipeline_reg_pp0_iter4_tmp_139_reg_422[0:0] === 1'b1) ? p_Val2_38_fu_350_p1 : p_Val2_s_fu_353_p2);

assign p_Val2_s_fu_353_p2 = ($signed(p_Val2_39_fu_58) + $signed(p_Val2_38_fu_350_p1));

assign r_fu_164_p2 = (Row_assign_phi_fu_112_p4 + ap_const_lv2_1);

assign tmp_134_fu_254_p2 = (tmp_mid2_cast_fu_250_p1 + tmp_150_cast_fu_200_p1);

assign tmp_136_fu_269_p2 = (tmp_i_i_cast_fu_265_p1 + tmp_150_cast_fu_200_p1);

assign tmp_137_fu_280_p3 = {{Col_assign_3_mid2_fu_234_p3}, {1'b0}};

assign tmp_138_fu_292_p2 = (tmp_mid2_cast_fu_250_p1 + tmp_155_cast_fu_288_p1);

assign tmp_139_fu_303_p2 = ((Col_assign_3_mid2_fu_234_p3 == ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_140_fu_309_p2 = ((Col_assign_3_mid2_fu_234_p3 == ap_const_lv2_1) ? 1'b1 : 1'b0);

assign tmp_150_cast_fu_200_p1 = tmp_fu_192_p3;

assign tmp_152_cast_fu_260_p1 = tmp_134_fu_254_p2;

assign tmp_153_cast_fu_275_p1 = tmp_136_fu_269_p2;

assign tmp_155_cast_fu_288_p1 = tmp_137_fu_280_p3;

assign tmp_156_cast_fu_298_p1 = tmp_138_fu_292_p2;

assign tmp_fu_192_p3 = {{tmp_mid2_v_fu_184_p3}, {1'b0}};

assign tmp_i_i_cast_fu_265_p1 = Col_assign_3_mid2_fu_234_p3;

assign tmp_mid2_cast_fu_250_p1 = tmp_mid2_fu_242_p3;

assign tmp_mid2_fu_242_p3 = ((exitcond_mid_fu_216_p2[0:0] === 1'b1) ? c_fu_222_p2 : Col_assign_mid_fu_176_p3);

assign tmp_mid2_v_fu_184_p3 = ((exitcond_flatten7_fu_170_p2[0:0] === 1'b1) ? r_fu_164_p2 : Row_assign_phi_fu_112_p4);

assign tmp_s_fu_228_p2 = (exitcond_mid_fu_216_p2 | exitcond_flatten7_fu_170_p2);

endmodule //matrix_multiply_defa
